In [1]:
import tqdm
import numpy as np
import multiprocessing
import uuid
import os
import threading
import time
import random
import math

In [2]:
from box_client import get_box_client
from annotation_processor import *

In [3]:
import tensorflow as tf
import tensorflow.contrib.layers as layers

In [4]:
seizure_annotations = load_seizure_annotations("seizure_annotations.json")

In [5]:
train_dir = "tmp"

In [6]:
def choose_epoch_files(n_files, files, seizure_annotations, p=0.5):
    n_pos = int(n_files * p)
    n_neg = n_files - n_pos
    
    positive_files = []
    negative_files = []
    for name in files:
        if len(seizure_times_from_npz_filename(name, seizure_annotations)) > 0:
            positive_files.append(name)
        else:
            negative_files.append(name)
    
    positive_examples = list(np.random.choice(positive_files, size=n_pos))
    negative_examples = list(np.random.choice(negative_files, size=n_neg))
    
    return positive_examples + negative_examples

In [7]:
# Function to generate vector y corresponding to  binary classification of video clips
# intervals of duration = window_length annotation in seconds
# seizure array will receive dictionary of video name of seizure times

def ground_truth_label(seizure_array, window_start, window_length):

   # Check if sliding window overlaps with seizure window
   for k in seizure_array:

       # Here just hard-coded 10 sec as minimum duration of seizure
       if (window_start + window_length > k) and (window_start < k + 10):
            return 1
       # Windows after the 10 sec minimum duration of seizure and less than 120 secs after seizure start
       if (window_start >= k + 10) and (window_start < k + 120):
            return -1

   # Return 0 for non-seizure windows
   return 0

In [8]:
def epoch_positive_negative_times(epoch_examples, window_length=5, fps=29.97):
    epoch_file_names = list(epoch_examples.keys())
    pos_example_indices = []
    neg_example_indices = []

    for file_idx, file_name in enumerate(epoch_file_names):
        processed_chunk = epoch_examples[file_name]
        # video times (sec)
        vid_start_time = processed_chunk["start_time"]
        vid_length = int(processed_chunk["features"].shape[0]/fps)
        vid_end_time = vid_start_time + vid_length
        seizure_times = seizure_times_from_npz_filename(file_name, seizure_annotations)
        for i in range(vid_length - window_length):
            label = ground_truth_label(seizure_times, vid_start_time + i, window_length)
            if label == 0:
                neg_example_indices.append((file_idx, i))
            elif label == 1:
                pos_example_indices.append((file_idx, i))
                
    return epoch_file_names, pos_example_indices, neg_example_indices

In [9]:
def indices_to_example(epoch_examples, epoch_filenames, pair, window_length = 5, fps = 30):
    file_index = pair[0]
    time_index = pair[1]
    features = epoch_examples[epoch_filenames[file_index]]['features']
    return features[time_index:time_index+window_length*fps]

In [10]:
def generate_minibatch(batch_size, pos_p, pos_example_indices, neg_example_indices, epoch_examples, epoch_filenames):
    num_pos_examples = int(batch_size*pos_p)
    num_neg_examples = batch_size - num_pos_examples
    
    pos_examples = random.choices(pos_example_indices, k=num_pos_examples)
    neg_examples = random.choices(neg_example_indices, k=num_neg_examples)
    
    batch_x = np.zeros((batch_size, 150, 1536))
    batch_y = np.zeros((batch_size, 1))
    
    
    for i in range(batch_size):
        if i < num_pos_examples:
            pair = pos_examples[i]
            batch_y[i] = 1
        else:
            pair = neg_examples[i - num_pos_examples]
            batch_y[i] = 0
        batch_x[i, :, :] = indices_to_example(epoch_examples, epoch_file_names, pair)
    
    return batch_x, batch_y

In [29]:
all_files = [f for f in os.listdir(train_dir) if os.path.isfile(os.path.join(train_dir, f))]

In [30]:
dev_set = set([
    '2019-01-18_6 up_73-3_MAH00011_8.npz',
    '2019-01-18_6 up_73-3_MAH00013_2.npz',
    '2019-01-18_6 up_74-1_MAH00016_0.npz',
    '2019-01-20_6 up_65-2_MAH00020_8.npz',
    '2019-01-18_6 up_68-2_MAH00014_8.npz',
    '2019-01-18_6 up_68-2_MAH00014_8.npz',
    '2019-01-20_6 up_68-2_MAH00019_6.npz',
    '2019-01-18_6 up_68-2_MAH00012_3.npz',
    '2019-01-18_6 up_70-1_MAH00015_7.npz',
    '2019-01-18_6 up_73-3_MAH00016_6.npz',
    '2019-01-18_6 up_68-2_MAH00014_0.npz',
    '2019-01-18_6 up_68-2_MAH00015_2.npz',
    '2019-01-18_6 up_68-2_MAH00011_8.npz',
    '2019-01-20_6 up_73-3_MAH00020_5.npz',
    '2019-01-18_6 up_68-2_MAH00015_2.npz',
    '2019-01-18_6 up_68-2_MAH00013_3.npz',
    '2019-01-20_6 up_65-2_MAH00021_2.npz',
    '2019-01-18_6 up_73-3_MAH00015_0.npz',
    '2019-01-20_6 up_74-1_MAH00019_8.npz',
    '2019-01-20_6 up_70-1_MAH00018_8.npz',
    '2019-01-20_6 up_74-1_MAH00018_7.npz',
    '2019-01-18_6 up_73-3_MAH00012_6.npz',
    '2019-01-20_6 up_73-2_MAH00018_1.npz',
    '2019-01-18_6 up_73-3_MAH00012_5.npz',
    '2019-01-18_6 up_70-1_MAH00014_2.npz',
    '2019-01-20_6 up_68-2_MAH00018_5.npz',
    '2019-01-18_6 up_70-1_MAH00014_9.npz',
    '2019-01-18_6 up_74-1_MAH00012_6.npz',
    '2019-01-18_6 up_73-2_MAH00011_5.npz',
    '2019-01-18_6 up_70-1_MAH00011_6.npz',
    '2019-01-20_6 up_68-2_MAH00020_5.npz',
    '2019-01-18_6 up_73-3_MAH00015_9.npz',
    '2019-01-18_6 up_73-2_MAH00011_1.npz',
    '2019-01-18_6 up_70-1_MAH00011_6.npz',
    '2019-01-18_6 up_65-2_MAH00014_6.npz',
    '2019-01-20_6 up_68-2_MAH00020_5.npz',
    '2019-01-20_6 up_70-1_MAH00018_6.npz',
    '2019-01-18_6 up_65-2_MAH00011_6.npz',
    '2019-01-18_6 up_73-2_MAH00011_6.npz',
    '2019-01-18_6 up_65-2_MAH00014_8.npz'
])

In [31]:
training_set = [f for f in all_files if f not in dev_set]

In [14]:
# Set up the network
RNN_HIDDEN = 256
INPUT_SIZE = 1536
OUTPUT_SIZE = 1 # 1 bit per timestep
LEARNING_RATE = 0.001
BATCH_SIZE = 128
FALSE_NEG_PEN = 100

In [15]:
inputs  = tf.placeholder(tf.float32, (None, None, INPUT_SIZE))  # (time, batch, in)
outputs = tf.placeholder(tf.float32, (None, OUTPUT_SIZE)) # (batch, out)

cell = tf.nn.rnn_cell.LSTMCell(RNN_HIDDEN, state_is_tuple=True)

In [16]:
initial_state = cell.zero_state(tf.shape(inputs)[0], tf.float32)
rnn_outputs, rnn_states = tf.nn.dynamic_rnn(cell, inputs, initial_state=initial_state)

In [21]:
# project output from rnn output size to OUTPUT_SIZE. Sometimes it is worth adding
# an extra layer here.
pred = tf.layers.dense(rnn_states[1], OUTPUT_SIZE, activation=tf.sigmoid)

In [38]:
error = tf.add(tf.multiply(tf.multiply(outputs, -tf.log(pred)), FALSE_NEG_PEN),
               tf.multiply(tf.subtract(1.0, outputs), -tf.log(tf.subtract(1.0, pred))))
error = tf.reduce_mean(error)
train_fn = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(error)

In [39]:
#Training Loop
n_epoch_files = 120
n_epochs = 40
pos_p = 1/2
batch_size = BATCH_SIZE
LEARNING_RATE = 1e-4


with tf.Session() as session:
    session.run(tf.global_variables_initializer())

    for epoch in tqdm.tqdm_notebook(range(n_epochs)):
        epoch_files = choose_epoch_files(n_epoch_files, training_set, seizure_annotations)
        epoch_examples = {}
        for file_name in epoch_files:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                epoch_examples[file_name] = example
                

        epoch_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(epoch_examples)
        n_minibatches = int((len(pos_example_indices)/pos_p)/batch_size)
        n_minibatches = 300
        epoch_error = 0.0
        for batch_i in tqdm.tqdm_notebook(range(n_minibatches)):
            batch_X, batch_Y = generate_minibatch(batch_size, pos_p, 
                                                  pos_example_indices, neg_example_indices, 
                                                  epoch_examples, epoch_file_names)
            
            epoch_error += session.run([error, train_fn], {
                inputs: batch_X,
                outputs: batch_Y,
            })[0]
            
        del epoch_examples
        
        dev_examples = {}
        for file_name in dev_set:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                dev_examples[file_name] = example
        
        epoch_error /= n_minibatches        
        print("Epoch %d, train error: %.4f" % (epoch+1, epoch_error))
                
        dev_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(dev_examples)
        dev_set_error = 0.0
        n_dev_examples = len(pos_example_indices) + len(neg_example_indices)
        n_dev_batches = math.ceil(n_dev_examples/BATCH_SIZE)
        
        if (epoch+1) % 4 == 0:
            conf_matrix = np.zeros((2,2))
            for batch_i in tqdm.tqdm_notebook(range(n_dev_batches)):
                offset = batch_i * BATCH_SIZE
                size = min(BATCH_SIZE, n_dev_examples - offset) 

                batch_X = np.zeros((size, 150, 1536))
                batch_Y = np.zeros((size, 1))


                for i in range(size):
                    if i + offset < len(pos_example_indices):
                        pair = pos_example_indices[i + offset]
                        batch_Y[i] = 1
                    else:
                        pair = neg_example_indices[i + offset - len(pos_example_indices)]
                        batch_Y[i] = 0
                    batch_X[i, :, :] = indices_to_example(dev_examples, dev_file_names, pair)

                predictions, err = session.run([pred, error], {
                    inputs: batch_X,
                    outputs: batch_Y
                })
                predictions = predictions.flatten()
                batch_Y = batch_Y.flatten()

                tp = np.sum((predictions >= 0.5) & (batch_Y == 1))
                fp = np.sum((predictions >= 0.5) & (batch_Y == 0))
                tn = np.sum((predictions < 0.5) & (batch_Y == 0))
                fn = np.sum((predictions < 0.5) & (batch_Y == 1))
                dev_set_error += err
                conf_matrix[0, 0] += tn
                conf_matrix[1, 0] += fn
                conf_matrix[0, 1] += fp
                conf_matrix[1, 1] += tp
        
            dev_set_error /= n_dev_batches       
            print("Dev set error: %.4f" % (dev_set_error))
            print(conf_matrix)

Epoch 1, train error: 2.3510


Epoch 2, train error: 1.7388


Epoch 3, train error: 1.7973


Epoch 4, train error: 1.5536


Dev set error: 2.6546
[[9812. 8728.]
 [  57.  181.]]


Epoch 5, train error: 1.2844


Epoch 6, train error: 1.2569


Epoch 7, train error: 1.6124


Epoch 8, train error: 1.5317


Dev set error: 3.3828
[[ 2324. 16216.]
 [    0.   238.]]


Epoch 9, train error: 1.2153


Epoch 10, train error: 0.8378


Epoch 11, train error: 0.6261


Epoch 12, train error: 1.0797


Dev set error: 3.7552
[[16432.  2108.]
 [  190.    48.]]


Epoch 13, train error: 0.8920


Epoch 14, train error: 0.8779


Epoch 15, train error: 0.4653


Epoch 16, train error: 0.8782


Dev set error: 5.5174
[[17322.  1218.]
 [  215.    23.]]


Epoch 17, train error: 0.5151


Epoch 18, train error: 1.6992


Epoch 19, train error: 1.7525


Epoch 20, train error: 1.1248


Dev set error: 5.9427
[[    0. 18540.]
 [    0.   238.]]


Epoch 21, train error: 1.6783


Epoch 22, train error: 1.1169


Epoch 23, train error: 0.4466


Epoch 24, train error: 0.8778


Dev set error: 4.6005
[[1.7144e+04 1.3960e+03]
 [2.2600e+02 1.2000e+01]]


Epoch 25, train error: 0.3311


Epoch 26, train error: 0.1942


Epoch 27, train error: 1.1594


Epoch 28, train error: 0.2077


Dev set error: 5.8671
[[1.8031e+04 5.0900e+02]
 [2.3000e+02 8.0000e+00]]


Epoch 29, train error: 0.1294


Epoch 30, train error: 0.9465


Epoch 31, train error: 0.2952


Epoch 32, train error: 1.4425


Dev set error: 3.5925
[[ 2430. 16110.]
 [    0.   238.]]


Epoch 33, train error: 1.5581


Epoch 34, train error: 0.5215


Epoch 35, train error: 0.5972


Epoch 36, train error: 0.3546


Dev set error: 7.0663
[[1.7402e+04 1.1380e+03]
 [2.3100e+02 7.0000e+00]]


Epoch 37, train error: 0.8106


Epoch 38, train error: 1.3687


Epoch 39, train error: 0.5217


Epoch 40, train error: 0.4628


Dev set error: 6.4976
[[1.8217e+04 3.2300e+02]
 [2.3300e+02 5.0000e+00]]


In [40]:
#Training Loop
n_epoch_files = 120
n_epochs = 40
pos_p = 1/2
batch_size = BATCH_SIZE
LEARNING_RATE = 1e-5

with tf.Session() as session:
    session.run(tf.global_variables_initializer())

    for epoch in tqdm.tqdm_notebook(range(n_epochs)):
        epoch_files = choose_epoch_files(n_epoch_files, training_set, seizure_annotations)
        epoch_examples = {}
        for file_name in epoch_files:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                epoch_examples[file_name] = example
                

        epoch_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(epoch_examples)
        n_minibatches = int((len(pos_example_indices)/pos_p)/batch_size)
        n_minibatches = 300
        epoch_error = 0.0
        for batch_i in tqdm.tqdm_notebook(range(n_minibatches)):
            batch_X, batch_Y = generate_minibatch(batch_size, pos_p, 
                                                  pos_example_indices, neg_example_indices, 
                                                  epoch_examples, epoch_file_names)
            
            epoch_error += session.run([error, train_fn], {
                inputs: batch_X,
                outputs: batch_Y,
            })[0]
            
        del epoch_examples
        
        dev_examples = {}
        for file_name in dev_set:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                dev_examples[file_name] = example
        
        epoch_error /= n_minibatches        
        print("Epoch %d, train error: %.4f" % (epoch+1, epoch_error))
                
        dev_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(dev_examples)
        dev_set_error = 0.0
        n_dev_examples = len(pos_example_indices) + len(neg_example_indices)
        n_dev_batches = math.ceil(n_dev_examples/BATCH_SIZE)
        
        if (epoch+1) % 4 == 0:
            conf_matrix = np.zeros((2,2))
            for batch_i in tqdm.tqdm_notebook(range(n_dev_batches)):
                offset = batch_i * BATCH_SIZE
                size = min(BATCH_SIZE, n_dev_examples - offset) 

                batch_X = np.zeros((size, 150, 1536))
                batch_Y = np.zeros((size, 1))


                for i in range(size):
                    if i + offset < len(pos_example_indices):
                        pair = pos_example_indices[i + offset]
                        batch_Y[i] = 1
                    else:
                        pair = neg_example_indices[i + offset - len(pos_example_indices)]
                        batch_Y[i] = 0
                    batch_X[i, :, :] = indices_to_example(dev_examples, dev_file_names, pair)

                predictions, err = session.run([pred, error], {
                    inputs: batch_X,
                    outputs: batch_Y
                })
                predictions = predictions.flatten()
                batch_Y = batch_Y.flatten()

                tp = np.sum((predictions >= 0.5) & (batch_Y == 1))
                fp = np.sum((predictions >= 0.5) & (batch_Y == 0))
                tn = np.sum((predictions < 0.5) & (batch_Y == 0))
                fn = np.sum((predictions < 0.5) & (batch_Y == 1))
                dev_set_error += err
                conf_matrix[0, 0] += tn
                conf_matrix[1, 0] += fn
                conf_matrix[0, 1] += fp
                conf_matrix[1, 1] += tp
        
            dev_set_error /= n_dev_batches       
            print("Dev set error: %.4f" % (dev_set_error))
            print(conf_matrix)

Epoch 1, train error: 2.3626


Epoch 2, train error: 1.3715


Epoch 3, train error: 1.6009


Epoch 4, train error: 1.5949


Dev set error: 2.3511
[[10164.  8376.]
 [   95.   143.]]


Epoch 5, train error: 1.3018


Epoch 6, train error: 0.9306


Epoch 7, train error: 1.4168


Epoch 8, train error: 2.0393


Dev set error: 2.3607
[[ 7072. 11468.]
 [   28.   210.]]


Epoch 9, train error: 1.3433


Epoch 10, train error: 1.1946


Epoch 11, train error: 0.7677


Epoch 12, train error: 1.2902


Dev set error: 2.3999
[[10786.  7754.]
 [  122.   116.]]


Epoch 13, train error: 1.7118


Epoch 14, train error: 1.1031


Epoch 15, train error: 0.8556


Epoch 16, train error: 0.8028


Dev set error: 5.8584
[[17449.  1091.]
 [  220.    18.]]


Epoch 17, train error: 1.6015


Epoch 18, train error: 1.0156


Epoch 19, train error: 0.7276


Epoch 20, train error: 0.7105


Dev set error: 9.3944
[[1.5000e+01 1.8525e+04]
 [0.0000e+00 2.3800e+02]]


Epoch 21, train error: 1.9818


Epoch 22, train error: 1.1044


Epoch 23, train error: 0.6929


Epoch 24, train error: 0.4160


Dev set error: 6.4822
[[1.7817e+04 7.2300e+02]
 [2.3200e+02 6.0000e+00]]


Epoch 25, train error: 0.7271


Epoch 26, train error: 2.8825


Epoch 27, train error: 1.4400


Epoch 28, train error: 0.5973


Dev set error: 3.3597
[[8780. 9760.]
 [  42.  196.]]


Epoch 29, train error: 0.7508


Epoch 30, train error: 1.0399


Epoch 31, train error: 0.4429


Epoch 32, train error: 0.1984


Dev set error: 6.3401
[[1.8067e+04 4.7300e+02]
 [2.3400e+02 4.0000e+00]]


Epoch 33, train error: 0.8856


Epoch 34, train error: 0.2871


Epoch 35, train error: 0.2895


Epoch 36, train error: 2.1641


Dev set error: 2.7986
[[ 5721. 12819.]
 [   14.   224.]]


Epoch 37, train error: 1.3038


Epoch 38, train error: 0.3127


Epoch 39, train error: 2.4062


Epoch 40, train error: 1.4641


Dev set error: 2.3155
[[9263. 9277.]
 [  79.  159.]]


In [41]:
error = tf.add(tf.multiply(tf.multiply(outputs, -tf.log(pred)), 10.0),
               tf.multiply(tf.subtract(1.0, outputs), -tf.log(tf.subtract(1.0, pred))))
error = tf.reduce_mean(error)
train_fn = tf.train.AdamOptimizer(learning_rate=LEARNING_RATE).minimize(error)

In [42]:
#Training Loop
n_epoch_files = 120
n_epochs = 40
pos_p = 1/2
batch_size = BATCH_SIZE
LEARNING_RATE = 1e-4

with tf.Session() as session:
    session.run(tf.global_variables_initializer())

    for epoch in tqdm.tqdm_notebook(range(n_epochs)):
        epoch_files = choose_epoch_files(n_epoch_files, training_set, seizure_annotations)
        epoch_examples = {}
        for file_name in epoch_files:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                epoch_examples[file_name] = example
                

        epoch_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(epoch_examples)
        n_minibatches = int((len(pos_example_indices)/pos_p)/batch_size)
        n_minibatches = 300
        epoch_error = 0.0
        for batch_i in tqdm.tqdm_notebook(range(n_minibatches)):
            batch_X, batch_Y = generate_minibatch(batch_size, pos_p, 
                                                  pos_example_indices, neg_example_indices, 
                                                  epoch_examples, epoch_file_names)
            
            epoch_error += session.run([error, train_fn], {
                inputs: batch_X,
                outputs: batch_Y,
            })[0]
            
        del epoch_examples
        
        dev_examples = {}
        for file_name in dev_set:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                dev_examples[file_name] = example
        
        epoch_error /= n_minibatches        
        print("Epoch %d, train error: %.4f" % (epoch+1, epoch_error))
                
        dev_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(dev_examples)
        dev_set_error = 0.0
        n_dev_examples = len(pos_example_indices) + len(neg_example_indices)
        n_dev_batches = math.ceil(n_dev_examples/BATCH_SIZE)
        
        if (epoch+1) % 4 == 0:
            conf_matrix = np.zeros((2,2))
            for batch_i in tqdm.tqdm_notebook(range(n_dev_batches)):
                offset = batch_i * BATCH_SIZE
                size = min(BATCH_SIZE, n_dev_examples - offset) 

                batch_X = np.zeros((size, 150, 1536))
                batch_Y = np.zeros((size, 1))


                for i in range(size):
                    if i + offset < len(pos_example_indices):
                        pair = pos_example_indices[i + offset]
                        batch_Y[i] = 1
                    else:
                        pair = neg_example_indices[i + offset - len(pos_example_indices)]
                        batch_Y[i] = 0
                    batch_X[i, :, :] = indices_to_example(dev_examples, dev_file_names, pair)

                predictions, err = session.run([pred, error], {
                    inputs: batch_X,
                    outputs: batch_Y
                })
                predictions = predictions.flatten()
                batch_Y = batch_Y.flatten()

                tp = np.sum((predictions >= 0.5) & (batch_Y == 1))
                fp = np.sum((predictions >= 0.5) & (batch_Y == 0))
                tn = np.sum((predictions < 0.5) & (batch_Y == 0))
                fn = np.sum((predictions < 0.5) & (batch_Y == 1))
                dev_set_error += err
                conf_matrix[0, 0] += tn
                conf_matrix[1, 0] += fn
                conf_matrix[0, 1] += fp
                conf_matrix[1, 1] += tp
        
            dev_set_error /= n_dev_batches       
            print("Dev set error: %.4f" % (dev_set_error))
            print(conf_matrix)

Epoch 1, train error: 1.0733


Epoch 2, train error: 0.6652


Epoch 3, train error: 0.4472


Epoch 4, train error: 0.3867


Dev set error: 0.6005
[[17041.  1499.]
 [  210.    28.]]


Epoch 5, train error: 0.2321


Epoch 6, train error: 0.3070


Epoch 7, train error: 0.5956


Epoch 8, train error: 0.2922


Dev set error: 0.7894
[[15158.  3382.]
 [  209.    29.]]


Epoch 9, train error: 0.2040


Epoch 10, train error: 0.3231


Epoch 11, train error: 0.1830


Epoch 12, train error: 0.1650


Dev set error: 0.6246
[[18218.   322.]
 [  238.     0.]]


Epoch 13, train error: 0.1397


Epoch 14, train error: 0.2682


Epoch 15, train error: 0.2019


Epoch 16, train error: 0.1282


Dev set error: 0.7346
[[18226.   314.]
 [  238.     0.]]


Epoch 17, train error: 0.1277


Epoch 18, train error: 0.1653


Epoch 19, train error: 0.1427


Epoch 20, train error: 0.1092


Dev set error: 0.7561
[[18284.   256.]
 [  238.     0.]]


Epoch 21, train error: 0.0566


Epoch 22, train error: 0.0944


Epoch 23, train error: 0.3648


Epoch 24, train error: 0.1677


Dev set error: 0.6704
[[1.7708e+04 8.3200e+02]
 [2.2400e+02 1.4000e+01]]


Epoch 25, train error: 0.1647


Epoch 26, train error: 0.1467


Epoch 27, train error: 0.0550


Epoch 28, train error: 0.1277


Dev set error: 0.8027
[[1.8142e+04 3.9800e+02]
 [2.3100e+02 7.0000e+00]]


Epoch 29, train error: 0.0867


Epoch 30, train error: 0.0439


Epoch 31, train error: 0.0508


Epoch 32, train error: 0.0303


Dev set error: 0.8799
[[1.8119e+04 4.2100e+02]
 [2.2600e+02 1.2000e+01]]


Epoch 33, train error: 0.1200


Epoch 34, train error: 0.0487


Epoch 35, train error: 0.0379


Epoch 36, train error: 0.1232


Dev set error: 0.7526
[[1.7655e+04 8.8500e+02]
 [2.2700e+02 1.1000e+01]]


Epoch 37, train error: 0.0713


Epoch 38, train error: 0.1490


Epoch 39, train error: 0.0497


Epoch 40, train error: 0.1166


Dev set error: 0.9182
[[1.8091e+04 4.4900e+02]
 [2.3000e+02 8.0000e+00]]


In [43]:
#Training Loop
n_epoch_files = 120
n_epochs = 40
pos_p = 1/2
batch_size = BATCH_SIZE
LEARNING_RATE = 1e-5

with tf.Session() as session:
    session.run(tf.global_variables_initializer())

    for epoch in tqdm.tqdm_notebook(range(n_epochs)):
        epoch_files = choose_epoch_files(n_epoch_files, training_set, seizure_annotations)
        epoch_examples = {}
        for file_name in epoch_files:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                epoch_examples[file_name] = example
                

        epoch_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(epoch_examples)
        n_minibatches = int((len(pos_example_indices)/pos_p)/batch_size)
        n_minibatches = 300
        epoch_error = 0.0
        for batch_i in tqdm.tqdm_notebook(range(n_minibatches)):
            batch_X, batch_Y = generate_minibatch(batch_size, pos_p, 
                                                  pos_example_indices, neg_example_indices, 
                                                  epoch_examples, epoch_file_names)
            
            epoch_error += session.run([error, train_fn], {
                inputs: batch_X,
                outputs: batch_Y,
            })[0]
            
        del epoch_examples
        
        dev_examples = {}
        for file_name in dev_set:
            with np.load(os.path.join(train_dir, file_name)) as data:
                example = {}
                example["features"] = data["features"]
                example["start_time"] = data["start_time"]
                dev_examples[file_name] = example
        
        epoch_error /= n_minibatches        
        print("Epoch %d, train error: %.4f" % (epoch+1, epoch_error))
                
        dev_file_names, pos_example_indices, neg_example_indices = epoch_positive_negative_times(dev_examples)
        dev_set_error = 0.0
        n_dev_examples = len(pos_example_indices) + len(neg_example_indices)
        n_dev_batches = math.ceil(n_dev_examples/BATCH_SIZE)
        
        if (epoch+1) % 4 == 0:
            conf_matrix = np.zeros((2,2))
            for batch_i in tqdm.tqdm_notebook(range(n_dev_batches)):
                offset = batch_i * BATCH_SIZE
                size = min(BATCH_SIZE, n_dev_examples - offset) 

                batch_X = np.zeros((size, 150, 1536))
                batch_Y = np.zeros((size, 1))


                for i in range(size):
                    if i + offset < len(pos_example_indices):
                        pair = pos_example_indices[i + offset]
                        batch_Y[i] = 1
                    else:
                        pair = neg_example_indices[i + offset - len(pos_example_indices)]
                        batch_Y[i] = 0
                    batch_X[i, :, :] = indices_to_example(dev_examples, dev_file_names, pair)

                predictions, err = session.run([pred, error], {
                    inputs: batch_X,
                    outputs: batch_Y
                })
                predictions = predictions.flatten()
                batch_Y = batch_Y.flatten()

                tp = np.sum((predictions >= 0.5) & (batch_Y == 1))
                fp = np.sum((predictions >= 0.5) & (batch_Y == 0))
                tn = np.sum((predictions < 0.5) & (batch_Y == 0))
                fn = np.sum((predictions < 0.5) & (batch_Y == 1))
                dev_set_error += err
                conf_matrix[0, 0] += tn
                conf_matrix[1, 0] += fn
                conf_matrix[0, 1] += fp
                conf_matrix[1, 1] += tp
        
            dev_set_error /= n_dev_batches       
            print("Dev set error: %.4f" % (dev_set_error))
            print(conf_matrix)

Epoch 1, train error: 1.5428


Epoch 2, train error: 0.6946


Epoch 3, train error: 0.3747


Epoch 4, train error: 0.2257


Dev set error: 0.6824
[[14463.  4077.]
 [  133.   105.]]


Epoch 5, train error: 0.2828


Epoch 6, train error: 0.2533


Epoch 7, train error: 0.1894


Epoch 8, train error: 0.1398


Dev set error: 0.6439
[[17999.   541.]
 [  238.     0.]]


Epoch 9, train error: 0.0863


Epoch 10, train error: 0.2138


Epoch 11, train error: 0.0916


Epoch 12, train error: 0.0859


Dev set error: 1.2881
[[1.5241e+04 3.2990e+03]
 [2.2400e+02 1.4000e+01]]


Epoch 13, train error: 0.2329


Epoch 14, train error: 0.0653


Epoch 15, train error: 0.4444


Epoch 16, train error: 0.1933


Dev set error: 0.6760
[[1.722e+04 1.320e+03]
 [2.340e+02 4.000e+00]]


Epoch 17, train error: 0.1165


Epoch 18, train error: 0.1272


Epoch 19, train error: 0.2161


Epoch 20, train error: 0.1280


Dev set error: 0.6643
[[18156.   384.]
 [  238.     0.]]


Epoch 21, train error: 0.1173


Epoch 22, train error: 0.0460


Epoch 23, train error: 0.0455


Epoch 24, train error: 0.0489


Dev set error: 0.6831
[[18223.   317.]
 [  238.     0.]]


Epoch 25, train error: 0.0751


Epoch 26, train error: 0.0706


Epoch 27, train error: 0.0456


Epoch 28, train error: 0.0606


Dev set error: 0.6744
[[18303.   237.]
 [  238.     0.]]


Epoch 29, train error: 0.0317


Epoch 30, train error: 0.0358


Epoch 31, train error: 0.0418


Epoch 32, train error: 0.0616


Dev set error: 0.7124
[[18505.    35.]
 [  238.     0.]]


Epoch 33, train error: 0.0473


Epoch 34, train error: 0.0603


Epoch 35, train error: 0.1076


Epoch 36, train error: 0.0830


Dev set error: 0.7718
[[18445.    95.]
 [  238.     0.]]


Epoch 37, train error: 0.0584


Epoch 38, train error: 0.0853


Epoch 39, train error: 0.0343


Epoch 40, train error: 0.0824


Dev set error: 0.7971
[[18417.   123.]
 [  238.     0.]]
